spring:
  jpa:
    hibernate:
      show-sql: true
      #      TODO : 실제 서비스 시 효율을 위해 show-sql true로 두지 않을 것.
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

  mvc:
    async:
      request-timeout: 1000


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://${mysql:lv3-mysqldb-ansoo.ccxmcbwnnwze.us-east-1.rds.amazonaws.com}:3306/TestDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #url: jdbc:mysql://${mysql:hellogptvmysql.cdillw7s0dxx.ap-northeast-2.rds.amazonaws.com}:3306/FromUser?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #username: admin
    #password: 8659653314
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PWD}

  data:
    mongodb:
      #uri: mongodb://lv3_user_mongo:sufferFromYou333@ec2-3-34-198-223.ap-northeast-2.compute.amazonaws.com:27017/VodRecoForView?authSource=admin
      #uri: mongodb://lv3_user_mongo:lv3Pwd@ec2-3-38-106-43.ap-northeast-2.compute.amazonaws.com:27017/mongoTestDB?authSource=admin
      uri: ${DB_URI}
      
server:
  tomcat:
    access-log:
      enabled: true
      basedir: .
      directory: logs
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      pattern: '%{yyyy-MM-dd HH:mm:ss}t %s %r %{User-Agent}i %{Referer}i %a %b'